import { forwardRef, useRef, useState } from "react";
import { getThumbUrl, getThumbUrlWebp, isFirebaseStorageUrl } from "@utils/mediaUtils";

interface ThumbImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  /** Original full-resolution URL (Firebase Storage, Cloudinary, local asset, etc.) */
  src: string;
  /** Size suffix matching the Resize Images extension config, e.g. "400x400" */
  thumbSize?: string;
  alt?: string;
}

/**
 * Drop-in <img> replacement for gallery thumbnails.
 *
 * - Firebase Storage URLs: replaced with the thumbnail path generated by the
 *   "Resize Images" extension (thumbnails/ subfolder, same token).
 * - Tries the original extension first (e.g. _400x400.jpg). If the image fails
 *   to load (404), falls back to the .webp variant (_400x400.webp) once.
 * - All other URLs (local assets, Cloudinary, etc.): passed through unchanged.
 * - Always sets loading="eager" for faster display.
 * - Forwards ref so parent components can read naturalWidth for cache detection.
 */
const ThumbImage = forwardRef<HTMLImageElement, ThumbImageProps>(
  ({ src, thumbSize = "400x400", alt = "", onError, ...props }, ref) => {
    const [fallbackSrc, setFallbackSrc] = useState<string | null>(null);
    const fallbackTried = useRef(false);

    const isFirebase = isFirebaseStorageUrl(src);
    const displaySrc = isFirebase
      ? (fallbackSrc ?? getThumbUrl(src, thumbSize))
      : src;

    const handleError = (e: React.SyntheticEvent<HTMLImageElement>) => {
      if (!fallbackTried.current && isFirebase) {
        fallbackTried.current = true;
        setFallbackSrc(getThumbUrlWebp(src, thumbSize));
      }
      onError?.(e);
    };

    return (
      // eslint-disable-next-line jsx-a11y/alt-text
      <img
        ref={ref}
        src={displaySrc}
        alt={alt}
        loading="eager"
        decoding="async"
        onError={handleError}
        {...props}
      />
    );
  }
);

ThumbImage.displayName = "ThumbImage";

export default ThumbImage;
